---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(dplyr)
library(bbplot)
```

```{r}
geographic_lables <- read_csv("geo.csv")
View(geographic_lables)
```

```{r}
cancer_data <- read_csv("canc.csv")
```


```{r}
borders_data <- cancer_data %>%
                      filter(HB == "S08000016") %>%
                      filter(CancerSite == "All cancer types")
                    
                      
ggplot(borders_data) +
  aes(x = Year, y = IncidencesAllAges, color = Sex) +
  geom_line()+
  scale_x_continuous("Years") +
  scale_y_continuous("Cancer Incidences") +
  geom_point()+
  bbc_style() +
  scale_colour_manual(values = c("#990000", "#FAAB18", "#1380A1")) +
  ggtitle(
    "NHS Borders Cancer Incidence",
     subtitle = "1994 - 2018"
  ) 
  
```
```{r}
open_data_border <- cancer_data %>%
                      filter(HB == "S08000016") %>%
                      filter(CancerSite != "All cancer types") %>%
                      filter(Sex == c("Male", "Female")) %>%
                      group_by(Sex) %>%
                      summarise(Total_Incidences = sum(IncidencesAllAges))
View(open_data_border)
                  
                      
                     
ggplot(open_data_border) +
  aes(x = Sex, y = Total_Incidences) +
  geom_col()+
  #scale_x_continuous("Years") +
  #scale_y_continuous("Total Number of Cancer Incidences") +
  theme_qb+
  scale_fill_manual(values = c('green', 'blue')) +
  ggtitle(
    "Total Incidence of cancer in NHS Borders 1994 - 2018",
    subtitle = "Total = 17,680 - Out of which Female - 8839 / Male - 8841"
  )
```


```{r}
top_cancer <- cancer_data %>%
                      filter(HB == "S08000016") %>%
                      filter(CancerSite != "All cancer types") %>%
                      group_by(CancerSite)  %>%
                      summarise(Total_Incidences = sum(IncidencesAllAges)) %>%
                      arrange(desc(Total_Incidences))
```

```{r}
top_six <- head(top_cancer)
```


```{r}
all_cancer_facets <- cancer_data %>%
                      filter(HB == "S08000016") %>%
                      filter(CancerSite != "All cancer types") %>%
                      group_by(CancerSite) 
  

ggplot(all_cancer_facets) +
  aes(x = Year, y = IncidencesAllAges, color = CancerSite) +
  geom_line()+
  scale_x_continuous("Years") +
  scale_y_continuous("Cancer Incidences") +
  facet_wrap(~ CancerSite) +
  theme(legend.position = "none")

```


```{r}
all_cancer_facets <- cancer_data %>%
                      filter(HB == "S08000016") %>%
                      filter(CancerSite != "All cancer types") %>%
                      group_by(CancerSite) 
  

ggplot(all_cancer_facets) +
  aes(x = Year, y = IncidencesAllAges, color = CancerSite) +
  geom_line()+
  scale_x_continuous("Years") +
  scale_y_continuous("Cancer Incidences") +
  facet_wrap(~ CancerSite) +
  theme(legend.position = "none")
```



```{r}
scotland_data <- read_csv("scotland.csv")
View(scotland_data)
```


```{r}
age_data <- cancer_data %>%
                      filter(HB == "S08000016") %>%
                      filter(CancerSite == "All cancer types")
                    
                      
ggplot(borders_data) +
  aes(x = Year, y = IncidencesAllAges, color = Sex) +
  geom_line()+
  scale_x_continuous("Years") +
  scale_y_continuous("Cancer Incidences") +
  geom_point()+
  bbc_style() +
  scale_colour_manual(values = c("#990000", "#FAAB18", "#1380A1")) +
  ggtitle(
    "NHS Borders Cancer Incidence",
     subtitle = "1994 - 2018"
  ) 
```

